name: "Paul Mycek's personal website"
url: "https://pmycek.github.io"
mardown: kramdown
theme: minima
header_pages:
  - index.md
  - research.md
  - publications.md
  - vitae.md
  - contact.md
sass:
    sass_dir: assets/css
    style: compressed
