name: "Paul Mycek's personal website"
url: "https://pmycek.github.io"
mardown: kramdown
header_pages:
  - index.md
  - research.md
  - publications.md
  - vitae.md
  - contact.md
sass:
    load_paths:
        - _sass
