name: "Paul Mycek's profesional website"
url: "https://pmycek.github.io"
author: Paul Mycek
email: mycek@cerfacs.fr
safe_email: "mycek [at] cerfacs [dot] fr"
phone: "+33 (0)5 61 19 30 23"
address: |
  Cerfacs
  42 avenue Gaspard Coriolis
  31057 Toulouse Cedex 01
  France
footer-links:
  scholar: https://scholar.google.com/citations?user=yzl1AKUAAAAJ
  orcid: https://orcid.org/0000-0002-6919-112X
  researchgate: https://www.researchgate.net/profile/Paul_Mycek
  publons: https://www.webofscience.com/wos/author/record/2982040
mardown: kramdown
theme: minima
header_pages:
  - index.md
  - research.md
  - publications.md
  - vitae.md
sass:
  sass_dir: _sass
  style: compressed
