name: "Paul Mycek's profesional website"
url: "https://pmycek.github.io"
author: Paul Mycek
email: mycek@cerfacs.fr
safe_email: "mycek [AT] cerfacs [DOT] fr"
address: |
  Cerfacs
  42 avenue Gaspard Coriolis
  31057 Toulouse Cedex 01
  France
footer-links:
  scholar: https://scholar.google.com/citations?user=yzl1AKUAAAAJ
mardown: kramdown
theme: minima
header_pages:
  - index.md
  - research.md
  - publications.md
  - vitae.md
  - contact.md
sass:
  sass_dir: _sass
  style: compressed
