name: "Paul Mycek's personal website"
url: "https://pmycek.github.io"
author: Paul Mycek
email: mycek@cerfacs.fr
description: |
  Cerfacs<br />
  42 avenue Gaspard Coriolis<br />
  31057 Toulouse Cedex 01<br />
  France
mardown: kramdown
theme: minima
header_pages:
  - index.md
  - research.md
  - publications.md
  - vitae.md
  - contact.md
sass:
  sass_dir: assets
  style: compressed
